apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: system-flux
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 1.2.6
  valuesFrom:
    - kind: Secret
      name: node-red-helm-values
      valuesKey: values.yaml
