apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: system-flux
      interval: 5m
  values:
    image:
      repository: linuxserver/calibre-web
      tag: 0.6.8-ls74
  valuesFrom:
    - kind: Secret
      name: calibre-web-helm-values
      valuesKey: values.yaml
